pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3912"
    }
    
    stages{
        stage('Echo Version') {
            steps {
                sh 'echo Print Maven Version'
                sh 'mvn -version'
            }
        }
        
        /*stage('Checkout') {
            steps {
                echo 'Cloning the Repo...'
                git url: 'https://github.com/Saikiran121/Certified-Jenkins-Engineer.git',
                    branch: 'main'
            }
        }*/
        
        stage('Build') {
            steps {
                echo 'Building Spring Boot Application...'
                dir('Simple-Maven-Application') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        
        stage('Unit Tests') {
            steps {
                echo 'Running JUnit tests...'
                dir('Simple-Maven-Application') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    // Generate Test Reports in Jenkins UI
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                echo 'Saving the executable JAR...'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }

        stage('Run Application') {
            steps {
                echo "Starting Spring Boot App in background on port ${params.APP_PORT}..."
                dir('Simple-Maven-Application') {
                    // JENKINS_NODE_COOKIE=dontKillMe prevents Jenkins from killing this background process when the stage ends
                    sh "JENKINS_NODE_COOKIE=dontKillMe nohup java -jar target/*.jar --server.port=${params.APP_PORT} > app.log 2>&1 &"
                }
            }
        }

        stage('Integration Testing') {
            steps {
                echo "Waiting for ${params.SLEEP_TIME} to ensure app is fully started..."
                sh "sleep ${params.SLEEP_TIME}"

                echo "Testing endpoint on port ${params.APP_PORT}..."
                sh "curl -s http://localhost:${params.APP_PORT}"
            }
        }
    }

    post {
        success {
            emailext attachLog: true, body: '$DEFAULT_CONTENT', replyTo: 'saikiranbiradar76642@gmail.com', subject: '$DEFAULT_SUBJECT', to: '$DEFAULT_RECIPIENTS'
        }
        failure {
            emailext attachLog: true, body: '$DEFAULT_CONTENT', replyTo: 'saikiranbiradar76642@gmail.com', subject: '$DEFAULT_SUBJECT', to: '$DEFAULT_RECIPIENTS'
        }
        always {
            echo 'Pipeline completed. Cleaning up background processes and workspace...'
            // Kill the application running on the specified port
            sh "fuser -k ${params.APP_PORT}/tcp || true"
            deleteDir()
        }
    }
}
