pipeline {
    agent any 

    tools {
        nodejs 'nodejs-24-13-0'
    }

    stages {
        stage('Check node version') {
            steps { 
                echo 'Checking node version...'
                sh 'node --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('NodeJs-Application') {
                    sh 'npm install --no-audit'
                }
            }
        }

        stage('NPM Dependency Audit') {
            steps {
                dir('NodeJs-Application') {
                    sh '''
                        npm audit --audit-level=high
                        echo $?
                    '''
                }
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dir('NodeJs-Application') {
                    dependencyCheck additionalArguments: '''
                        --scan .
                        --format ALL
                        --prettyPrint
                        --project "NodeJs-Application"
                        --out ./dependency-check-report
                    ''', odcInstallation: 'OWASP-DepCheck-12'
                }
            }
        }
    }
}