pipeline {
    agent any 

    tools {
        nodejs 'nodejs-24-13-0'
    }

    stages {
        stage('Check node version') {
            steps { 
                echo 'Checking node version...'
                sh 'node --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('NodeJs-Application') {
                    sh 'npm install --no-audit'
                }
            }
        }

        stage('Dependency Scanning') {
            parallel{
                stage('NPM Dependency Audit') {
                    steps {
                        dir('NodeJs-Application') {
                            sh '''
                                npm audit --audit-level=high
                                echo $?
                            '''
                        }
                    }
                }

                stage('OWASP Dependency Check') {
                    steps {
                        dir('NodeJs-Application') {
                            withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_KEY')]) {
                                dependencyCheck additionalArguments: '''
                                    --scan .
                                    --format ALL
                                    --prettyPrint
                                    --project "NodeJs-Application"
                                    --nvdApiKey ${NVD_KEY}
                                    --out ./dependency-check-report
                                ''', odcInstallation: 'OWASP-DepCheck-12'

                                dependencyCheckPublisher failedNewCritical: 1, failedNewHigh: 1, failedTotalCritical: 1, failedTotalHigh: 1, pattern: '**/dependency-check-report.xml'
                            }
                        }
                    }
                }
            }
        }
    }
}